// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertConfirmCareController from "./alert_confirm_care_controller"
application.register("alert-confirm-care", AlertConfirmCareController)

import AlertConfirmController from "./alert_confirm_controller"
application.register("alert-confirm", AlertConfirmController)

import AlertExerciseController from "./alert_exercise_controller"
application.register("alert-exercise", AlertExerciseController)

import AlertbysweetController from "./alertbysweet_controller"
application.register("alertbysweet", AlertbysweetController)

import AppointmentController from "./appointment_controller"
application.register("appointment", AppointmentController)

import CheckClickController from "./check_click_controller"
application.register("check-click", CheckClickController)

import CheckClickTimeController from "./check_click_time_controller"
application.register("check-click-time", CheckClickTimeController)

import CheckPrescriptionController from "./check_prescription_controller"
application.register("check-prescription", CheckPrescriptionController)

import ConfirmPillController from "./confirm_pill_controller"
application.register("confirm-pill", ConfirmPillController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import FlatpickrPrescriptionController from "./flatpickr_prescription_controller"
application.register("flatpickr-prescription", FlatpickrPrescriptionController)

import FormController from "./form_controller"
application.register("form", FormController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InitTomSelectController from "./init_tom_select_controller"
application.register("init-tom-select", InitTomSelectController)

import LoadImageController from "./load_image_controller"
application.register("load-image", LoadImageController)

import MapController from "./map_controller"
application.register("map", MapController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import UploadSelfyController from "./upload_selfy_controller"
application.register("upload-selfy", UploadSelfyController)
